### ISSUE TITLE
Top nav fixed causes layout shift on popover open

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#2345]
https://github.com/user-attachments/assets/0135350d-a8d7-47a2-9543-e631cff77acd

to see how it should work try toggling position: fixed from the nav

See https://github.com/Sendouc/sendou.ink/issues/2163

**Comment by hfcRed** [comment]
Hacky workaround:

```css
html {
    scrollbar-gutter: stable;
    padding-right: 0 !important;
}
```

Usually libraries apply ``overflow: hidden`` to the body rather than the html element to avoid things like this, and its also the reason why we cant use sticky in the first place. There unfortunately does not seem to be a config for which element React Aria applies its overflow styles to, so this is the best I can come up with
